import type { Metadata, Viewport } from "next";
import localFont from "next/font/local";
import "./globals.css";

const pretendard = localFont({
    src: [
        {
            path: "../public/fonts/PretendardVariable.woff2",
            weight: "400",
            style: "normal",
        },
        {
            path: "../public/fonts/PretendardVariable.woff2",
            weight: "600",
            style: "normal",
        },
    ],
    variable: "--font-pretendard",
    display: "swap",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export const viewport: Viewport = {
    width: "device-width",
    initialScale: 1,
    maximumScale: 1,
    userScalable: false,
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="ko">
            <head>
                <link
                    rel="stylesheet"
                    as="style"
                    crossOrigin="anonymous"
                    href="https://cdn.jsdelivr.net/gh/orioncactus/pretendard@v1.3.9/dist/web/variable/pretendardvariable.min.css"
                />
                <link rel="manifest" href="/manifest.json" />
                <meta name="theme-color" content="#b6771d" />
                <meta name="apple-mobile-web-app-capable" content="yes" />
                <meta
                    name="apple-mobile-web-app-status-bar-style"
                    content="default"
                />
                <meta name="apple-mobile-web-app-title" content="오늘은?" />
            </head>
            <body className={`${pretendard.variable} px-4 antialiased`}>
                {children}
            </body>
        </html>
    );
}
